//auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

//profile
export const UPDATE_USER = "UPDATE_USER";
export const CLEAR_USER = "CLEAR_USER";
export const GET_FAVORITES = "GET_FAVORITES";
export const DELETE_FAVORITE_LINE = "DELETE_FAVORITE_LINE";

//loading
export const REQUEST = "REQUEST";
export const SUCCESS = "SUCCESS";
export const FAILURE = "FAILURE";

//alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//admin¸
export const GET_SCHEDULE_LIST = "GET_SCHEDULE_LIST";
export const GET_LINE_SCHEDULE_FILE = "GET_LINE_SCHEDULE_FILE";
export const REMOVE_LINE_SCHEDULE_FILE = "REMOVE_LINE_SCHEDULE_FILE";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";

//schedule
export const GET_LINE_SCHEDULE_REQUEST = "GET_LINE_SCHEDULE_REQUEST";
export const GET_LINE_SCHEDULE_SUCCESS = "GET_LINE_SCHEDULE_SUCCESS";
export const GET_LINE_SCHEDULE_FAILURE = "GET_LINE_SCHEDULE_FAILURE";
export const REMOVE_LINE_SCHEDULE = "REMOVE_LINE_SCHEDULE";
export const GET_AUTOCOMPLETE_RESULTS = "GET_AUTOCOMPLETE_RESULTS";
export const GET_AUTOCOMPLETE_RESULTS_FAILURE =
    "GET_AUTOCOMPLETE_RESULTS_FAILURE";
export const REMOVE_AUTOCOMPLETE_RESULTS = "REMOVE_AUTOCOMPLETE_RESULTS";
